### ISSUE TITLE
Unable to convert Ruby value `"bplist00

### ISSUE THREAD

**Issue by Tauri4n** [Alua-Kinzhebayeva/iOS-PDF-Reader#13]
FYI: I get the following error when running pod install.

`Unable to convert Ruby value "bplist00\xD1\u0001\u0002_\u0010\u000FWebMainResource\xD5\u0003\u0004\u0005\u0006\a\b\t\n\v\f^WebResourceURL_\u0010\u000FWebResourceData_\u0010\u0013WebResourceMIMEType_\u0010\eWebResourceTextEncodingName_\u0010\u0014WebResourceFrameName_\u0010Qhttps://raw.githubusercontent.com/Alua-Kinzhebayeva/iOS-PDF-Reader/master/LICENSEO\u0011\u0004\xC4<html><head><style type=\"text/css\"></style></head><body><pre style=\"word-wrap: break-word; white-space: pre-wrap;\">The MIT License (MIT)\n\nCopyright (c) 2015 Alua-Kinzhebayeva\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n\n</pre></body></html>Ztext/plainUUTF-8P\u0000\b\u0000\v\u0000\u001D\u0000(\u00007\u0000I\u0000_\u0000}\u0000\x94\u0000\xE8\u0005\xB0\u0005\xBB\u0005\xC1\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0005\xC2"' into a CFTypeRef.`

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6c3573b3ac5426c60881e364c42c80a6b37fe2ac
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IZLA_QR' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IZLA_QR
pod 'PDFReader', '1.0.0'

  target 'IZLA_QRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

**Comment by ranunez** [comment]
Thats strange, this may or may not be related to https://github.com/CocoaPods/CocoaPods/issues/5200 ?

**Comment by ranunez** [comment]
Whats weird is that you weren't given a stack trace, it tried to somehow display the `LICENSE` file to the console for some reason

**Comment by Tauri4n** [comment]
I thought it had something to do with not being on the latest version of Ruby. I upgraded but I wasn't able to get CocoaPods to use the new version. Restarted, reset everything and tried again and it's working.
