### ISSUE TITLE
URL Request

### ISSUE THREAD

**Issue by alexviquez** [Alua-Kinzhebayeva/iOS-PDF-Reader#14]
Hello Friend, im actually using PDFReader my question is the next, can i request PDF from url with this Framework? if it yes, how can i? Thank You so much!

**Comment by ranunez** [comment]
I'm sorry, I'm not quite sure I understand your question "can i request PDF from url". Can you be a little more clear/specific? Do you want to download a PDF from a webpage and display it with this library? Thanks

**Comment by alexviquez** [comment]
yes, I would like to display a PDF file from a server and display with this Framework, Thanks

**Comment by ranunez** [comment]
You would need to download and save the file somehow, in order to create a `PDFDocument`. Something like this:

```swift
private func downloadAndDisplayPDF() {
    let url = NSURL(string: "http://images.apple.com/environment/pdf/products/watch/AppleWatch_PER_sept2015.pdf")!
    let data = NSData(contentsOfURL: url)
    let cachesDirectory = NSFileManager.defaultManager().URLsForDirectory(.CachesDirectory, inDomains: .UserDomainMask).first!
    
    do {
	    let documentsFolder = cachesDirectory.URLByAppendingPathComponent("documents")
	    try NSFileManager.defaultManager().createDirectoryAtURL(documentsFolder, withIntermediateDirectories: true, attributes: nil)
		    
	    let tempFileURL = documentsFolder.URLByAppendingPathComponent("example").URLByAppendingPathExtension("pdf")
	    try data?.writeToURL(tempFileURL, options: .AtomicWrite)
		    
	    let document = PDFDocument(fileURL: tempFileURL)
	    showDocument(document)
    } catch {
	    print("Failed")
    }
}
```

**Comment by foobra** [comment]
can we download part of the remote pdf and display it as progressive way?
