### ISSUE TITLE
Sharing PFD file with other apps

### ISSUE THREAD

**Issue by PanosSakkos** [Alua-Kinzhebayeva/iOS-PDF-Reader#23]
Hello Alua,

First of all, thanks for the great work!
Your pod is happily being used in [Dono for iOS](https://github.com/dono-app/dono-ios), let me know if you are interested in joining the test ring 😄 

Second, how about enabling to share the pdf file on other apps?
For example in the iBooks app you can either print the pdf or share it via email.

Thanks again for the effort!
:panos

edit: 

I just noticed in the README

> Customize the action button by replacing the UIBarButtonItem displayed with your own

So it's actually possible to inject it into the framework, good stuff! 😄

**Comment by ranunez** [comment]
Please check out our new 2.1.0 release. It lets you specify a custom `ActionStyle`, with one of the options to present an activity sheet (`.activitySheet `), enabling users to open/share the PDF in other apps!

**Comment by PanosSakkos** [comment]
Great! An code sample doing that would be great though 😉

**Comment by Alua-Kinzhebayeva** [comment]
@PanosSakkos thank you for your kind words! 
I like your project by the way!

**Comment by anandabayu** [comment]
Hi, I used .activitySheet I can share the pdf file to WhatsApp or save to file, but when I share it via Gmail, the document got an error, file name, and extension are changed.

[See Image](https://imgur.com/a/4cokhsk)
