### ISSUE TITLE
Flicker in UIPageViewController's views

### ISSUE THREAD

**Issue by romanvolkov-io** [Alua-Kinzhebayeva/iOS-PDF-Reader#27]
Hi,

I've integrated the PDFPageView into a UIPageViewController's view so that I can use a page controller instead of a collection view.

However, the screen flickers if it is being initially rendered. This behaviour is not present in a collection view. Scroll mode is worse than page curl.

Do I have to set any properties on the view, which hosts the PDFPageView? I don't use Storyboards.

**Comment by ranunez** [comment]
Hmm, nothing initially jumps out at me. Do you have a simple example repo of a `PDFPageView` in a `UIPageViewController`? `PDFPageView` is an `internal` class and wasn't intended to be used outside of the context of the framework.

**Comment by romanvolkov-io** [comment]
I'll create a sample project. I use a similar implementation, so I swapped classes and got the same result.

BTW, has this issue in CoreGraphics been resolved meanwhile?

`class PdfTiledLayer: CATiledLayer {
    override class func fadeDuration() -> CFTimeInterval {
        return 0.001 // Workaround
    }`

    `override func display() {
        //contents = nil   --> Stops the flickering but causes blinking instead
        super.display()
    }
}`

**Comment by romanvolkov-io** [comment]
I could pin down the part that's responsible for the issue mentioned above. It's this line:
```swift
contentScaleFactor = 1
```
Commenting out …
```swift
// contentScaleFactor = 1
```
… solves it. What's the implication not setting this property to one? Everything renders fine and quite fast!

**Comment by ranunez** [comment]
https://github.com/Alua-Kinzhebayeva/iOS-PDF-Reader/blob/master/Sources/Classes/PDFPageView.swift#L132

**Comment by ranunez** [comment]
But having said that, if the commenting out the above code works for you in your implementation, then go for it!
