### ISSUE TITLE
Slow thumbnail generation on large documents

### ISSUE THREAD

**Issue by romanvolkov-io** [Alua-Kinzhebayeva/iOS-PDF-Reader#28]
Hi,

Large documents (500+ pages) exhibit a significant delay if opened which is apparently caused by the thumb bar.

Any ideas how to improve this?

**Comment by ranunez** [comment]
Hmm, interesting I don't think many of us have tested this on that large of a PDF! A good solution would be to lazy load the thumbnail images in the background instead of having to wait to load all of them to display the PDF. Thanks for the catch!

**Comment by Niphery** [comment]
Same issue here. Loading a regular size magazine, (~120 pages) takes almost 7seconds.

**Comment by ranunez** [comment]
@romanvolkov-io @Niphery Performance should be dramatically better in [2.1.6](https://github.com/Alua-Kinzhebayeva/iOS-PDF-Reader/releases/tag/2.1.6), please let me know if this fixes it!

**Comment by Niphery** [comment]
@ranunez It's way better yes thank you for the reactivity 👍 
However the thumbnail preview take some times to load the first time I open the PDF.
Not really an issue at the moment but I though i would let you know.

**Comment by romanvolkov-io** [comment]
Yeah, I've already implemented something like that in a customer project recently. I also store generated thumbnails for caching purposes and regenerate them on demand.
