### ISSUE TITLE
Apps cannot running when it downloaded directly

### ISSUE THREAD

**Issue by mahdidham** [Alua-Kinzhebayeva/iOS-PDF-Reader#29]
Hi, i want to try download directly this apps from github(without using CocoaPods or Carthage). When i want to build it, it successfully run but iPhone simulator does not appear. Is that anything wrong to me? can you explain how?

**Comment by ranunez** [comment]
I'm not really sure I understand what you are trying to do, are you trying to run the demo project? If so, is it set to the Demo scheme with a simulator that you want to run it on? There might be some Xcode tutorials out there if you're unsure how this works.

**Comment by mahdidham** [comment]
Thank you, the problem was solved! Thank you too for the information.
