### ISSUE TITLE
open pdf using url

### ISSUE THREAD

**Issue by suresh777** [Alua-Kinzhebayeva/iOS-PDF-Reader#47]
i am using this pdf reader it is working fine but everytime if i want to display pdf i have to save,
 is there any way to open directly with url

**Comment by ranunez** [comment]
@suresh777 That is currently not a supported feature by the api, but you can easily create your own function [like this](https://github.com/Alua-Kinzhebayeva/iOS-PDF-Reader/issues/14#issuecomment-233974249) that accomplishes the same thing
