### ISSUE TITLE
Need to remove 'final' in PDFViewController class definition

### ISSUE THREAD

**Issue by iBenjamin** [Alua-Kinzhebayeva/iOS-PDF-Reader#48]
I need to inherit from PDFViewController to add some custom UIView above vc's view, but i find that PDFViewController can not be inherited. So can you remove the 'final' in the PDFViewController?

**Comment by ranunez** [comment]
This class was intentionally made `public` and not `open` for a reason, this isn't a trivial change. I do not want to support this functionality at this time and have to fix the many problems that could arise from subclassing PDFViewController incorrectly, and have to tip toe future modifications to many functions and inadvertently break any subclasses. A much cleaner solution would be to find out what exactly you need, and see if theres a way to reasonably accommodate this without subclassing (one does not need to subclass a view controller to overlay custom views on top of it).

**Comment by iBenjamin** [comment]
ok, i understand thank you!
