### ISSUE TITLE
Get table of content PDF file

### ISSUE THREAD

**Issue by NhatQuangZ** [Alua-Kinzhebayeva/iOS-PDF-Reader#49]
Hi. Your lib is great. But how i can get Table of content within pdf?

**Comment by ranunez** [comment]
What do you mean by "Table of content"?

**Comment by NhatQuangZ** [comment]
Some PDF have "table of content " associated, like this:
<img width="472" alt="screen shot 2017-03-18 at 1 14 21 pm" src="https://cloud.githubusercontent.com/assets/20753825/24069541/0a204780-0bdd-11e7-9601-895b4c854a38.png">
In ios, how i can get it?

**Comment by ranunez** [comment]
The bottom thumbnail bar serves this purpose by providing a visual table of contents of sorts. A textual representation of this is currently not supported.

**Comment by NhatQuangZ** [comment]
I know that, but do you have a suggest how i can do that? I really need this feature.

**Comment by ranunez** [comment]
You can do some digging around in the [documentation](https://developer.apple.com/reference/coregraphics/cgpdfdocument), but stackoverflow would be a more appropriate environment for you to try to get this question answered. Feel free to open up a pull request if you ever find a solution!
