### ISSUE TITLE
Add Swift 3 support

### ISSUE THREAD

**Issue by ranunez** [Alua-Kinzhebayeva/iOS-PDF-Reader#5]
Lets create a separate branch so we can add Swift 3 support

**Comment by ranunez** [comment]
@Alua-Kinzhebayeva If you create a `swift3` branch on this repo, I can add support for it from [my branch in my fork](https://github.com/ranunez/iOS-PDF-Reader/tree/swift3)

**Comment by Alua-Kinzhebayeva** [comment]
@ranunez good idea. will do

**Comment by Alua-Kinzhebayeva** [comment]
done 😄

**Comment by ranunez** [comment]
This issue was fixed with #7
