### ISSUE TITLE
How to go to specific page?

### ISSUE THREAD

**Issue by NhatQuangZ** [Alua-Kinzhebayeva/iOS-PDF-Reader#50]
I want to navigate to specific page in pdf? How i can do that?

**Comment by ranunez** [comment]
@NhatQuangZ Tap on the appropriate page on the bottom thumbnail bar to jump to a specific page

**Comment by clovs** [comment]
Hello,
How to open PDF to a specific page?
I want to read some Manga in PDF, I have to start from the last page.
regards,

**Comment by ranunez** [comment]
As stated above, there is currently no support in the library to do this, but you can open up a pull request if you would like to have it open to a specific page and I would be happy to take a look at it! :)

**Comment by ranunez** [comment]
@clovs [v2.4](https://github.com/Alua-Kinzhebayeva/iOS-PDF-Reader/releases/tag/2.4.0) now has the ability to open up a PDF to a specific page.

**Comment by clovs** [comment]
I was just watching how to do it.
You have been very reactive!
Thanks,
