### ISSUE TITLE
How to change cell size ?

### ISSUE THREAD

**Issue by reza-khalafi** [Alua-Kinzhebayeva/iOS-PDF-Reader#54]
Hello  
I want to change size of PDF and fit it to view controller 
![2017-04-23 11 01 10](https://cloud.githubusercontent.com/assets/8235321/25311357/2dac3918-2814-11e7-91ac-f43fd33fa1f0.jpg)

**Comment by ranunez** [comment]
You want it to zoom in? I am not sure I understand what you are asking

**Comment by reza-khalafi** [comment]
ohhhh , mistake  :(
