### ISSUE TITLE
Display progress hud

### ISSUE THREAD

**Issue by SeRcCaN** [Alua-Kinzhebayeva/iOS-PDF-Reader#56]
is it possible to use progress hud while using remote url. Until the download is finished

**Comment by SeRcCaN** [comment]
yes this is possible with DispatchQueue.main.async

**Comment by fukemy** [comment]
hello, i found the delay ~ 10 second when open pdf url with large content, so i want to display progress hud while opening until the pdfcontroller is showing, can you help me know where need to put that code?
