### ISSUE TITLE
Issue running on iOS 9.3.5

### ISSUE THREAD

**Issue by boynamanh** [Alua-Kinzhebayeva/iOS-PDF-Reader#61]
Can't touch on screen if pdf file contain more than 2 images,look like userinteraction property was false

**Comment by ranunez** [comment]
Sorry, can you be a little more specific? Do you mean you can't tap anywhere on the screen if it contains more than 2 pages?

**Comment by boynamanh** [comment]
That right,I can't swipe right to move to the next page

2017-09-18 23:26 GMT+07:00 Ricardo Nunez <notifications@github.com>:

**Comment by ranunez** [comment]
Can you please provide steps to reproduce? I can't reproduce this on the demo app.

**Comment by boynamanh** [comment]
Hi guy,
Oh sorry,long time ago after i did that, i can’t remember there steps :(
