### ISSUE TITLE
How to install manually without Cocoapod, or Carthage?

### ISSUE THREAD

**Issue by mahdidham** [Alua-Kinzhebayeva/iOS-PDF-Reader#69]
Can you descript how to install manually (download directly in github) without any use of Pod? Is it just copy-drag the PDFReader.Framework to my project or something else?

**Comment by ranunez** [comment]
Please consult Apple's documentation for how to embed a framework into an Xcode project: https://developer.apple.com/library/content/technotes/tn2435/_index.html
