### ISSUE TITLE
PDFReader 2.5.1 is not recognized as a Swift4 project

### ISSUE THREAD

**Issue by MarcoFilosi** [Alua-Kinzhebayeva/iOS-PDF-Reader#70]
PDFReader 2.5.1 has been written in Swift4 but CocoaPods 1.3.1 install it as a Swift 3.2 project

### Version Info

* PDFReader version: 2.5.1
* CocoaPods version: 1.3.1
* XCode version: 9.1 (9B55)

### Expected Behavior

Execute `pod install` and then compile project on XCode as a Swift 4 project.

### Actual Behavior

20 Swift Compiler Errors. Error messages are: `xxx is inaccessible due to 'private' protection level` 

### Steps to Reproduce

1. Install XCode 9.1 and CocoaPods 1.3.1
2. Run a project that depends on PDFReader 2.5.1
3. XCode cannot compile project because of PDFReader errors

**Comment by MarcoFilosi** [comment]
This is not an issue on PDFReader Pod. This is an issue on CocoaPods when we have project importing pods set to a specific swift version but pod is configured with another swift version.

**Comment by zaifz** [comment]
Go to PDFReader Target - BuildSettings. Select Swift Language Version as **Swift 4**

![screen shot 2018-02-27 at 5 13 15 pm](https://user-images.githubusercontent.com/16377770/36727226-8396e572-1be2-11e8-8c4b-1fe8fe19418e.png)
