### ISSUE TITLE
Names conflcts in iOS11

### ISSUE THREAD

**Issue by Neogene** [Alua-Kinzhebayeva/iOS-PDF-Reader#75]
PDFDocument is now an official iOS 11 class, so using this project for conditional code to display in iOS<11 pdf documents isn't working, any clue to use both? (ps: using into an obj-c project)

**Comment by ranunez** [comment]
The naming conflict is for a class in PDFKit (the native replacement for this library that is iOS 11 only). To avoid naming conflicts with this class, use [proper namespacing](http://en.swifter.tips/namespace/) or don't import PDFKit
