### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by IrfanMarwat** [Alua-Kinzhebayeva/iOS-PDF-Reader#76]
Unable to compile Xcode 9 swift 3.2. Lot of internal error, inaccessible due private protection level.

**Comment by ranunez** [comment]
https://github.com/Alua-Kinzhebayeva/iOS-PDF-Reader/blob/master/README.md#requirements

**Comment by zaifz** [comment]
Go to PDFReader Target - BuildSettings. Select Swift Language Version as **Swift 4**

![screen shot 2018-02-27 at 5 13 15 pm](https://user-images.githubusercontent.com/16377770/36727124-1f7a1d84-1be2-11e8-9104-cdc75bd47f84.png)
