### ISSUE TITLE
First two pages and last page are adding extra white spaces

### ISSUE THREAD

**Issue by veekay12345** [Alua-Kinzhebayeva/iOS-PDF-Reader#77]
Is there any way to remove the white spaces in the first 2 images and last image?

**Comment by ranunez** [comment]
@veekay12345 Do you have a screenshot of what you are referring to?

**Comment by veekay12345** [comment]
![screen shot 2017-11-24 at 11 20 29 am](https://user-images.githubusercontent.com/33084580/33197281-6ec11c80-d10a-11e7-8dfd-d08ed834ae70.png)

**Comment by ranunez** [comment]
@veekay12345 Do you have any steps to reproduce? I'm not sure what I am looking at.
