### ISSUE TITLE
Push first version to the Cocoapods repo

### ISSUE THREAD

**Issue by ranunez** [Alua-Kinzhebayeva/iOS-PDF-Reader#9]
1.  [Create an account to get set up with trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk)
2. [Create a release and push it](https://guides.cocoapods.org/making/making-a-cocoapod.html#release)

**Comment by Alua-Kinzhebayeva** [comment]
👍

**Comment by ranunez** [comment]
@Alua-Kinzhebayeva we should publish a v 1.0.0 (or < 1.0.0) real soon, so that other users can more easily integrate this with their own projects using cocoapods. As an alternative, if you add me as a colaborator, I can take care of doing this work for you so you don't have to worry about it 😀

**Comment by Alua-Kinzhebayeva** [comment]
@ranunez, done! added you as a collaborator 😉
